apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: demoapp=bygi/devops-toolkit
    argocd-image-updater.argoproj.io/demoapp.update-strategy: latest
    #argocd-image-updater.argoproj.io/bygi/devops-toolkit.allow-tags: regexp:^staging-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/demoapp.allow-tags: regexp:^staging.[0-9]+.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization:../../overlays/staging
    argocd-image-updater.argoproj.io/git-branch: staging
spec:
  project: staging
  source:
    repoURL: https://github.com/bogiepam/argo-cd-image-updater
    targetRevision: staging
    path: kustomize/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
