apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    #argocd-image-updater.argoproj.io/image-list: demoapp=bygi/devops-toolkit
    #argocd-image-updater.argoproj.io/demoapp.update-strategy: semver
    ##argocd-image-updater.argoproj.io/bygi/devops-toolkit.allow-tags: regexp:^staging-[0-9a-zA-Z]+$
    #argocd-image-updater.argoproj.io/demoapp.allow-tags: regexp:^prod.[0-9]+.[0-9]+$
    #argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    #argocd-image-updater.argoproj.io/write-back-target: kustomization:../../overlays/production
    #argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: production
  source:
    repoURL: https://github.com/bogiepam/argo-cd-image-updater
    targetRevision: HEAD
    path: kustomize/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
      allowEmpty: false
